Vagrant.configure("2") do |config|
  # Ubuntu 18.04 LTS
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "sf-practice"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
    vb.cpus = 1
  end

  # Копируем пустой файл на ВМ
  config.vm.provision "file", source: "empty_file.txt", destination: "/home/vagrant/empty_file.txt"

  # Установка пакетов и Python-библиотек
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip
    pip3 install psycopg2-binary django
    echo "Done! Python3, pip3, psycopg2 and Django installed."
  SHELL
end
